/* tslint:disable */
/* eslint-disable */
/**
 * Swagger Petstore - OpenAPI 3.0
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.11
 * Contact: apiteam@swagger.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface Address
 */
//Adress 인터페이스 정의
export interface Address {

    /**
     * @type {string}
     * @memberof Address
     * @example 437 Lytton
     */
    street?: string;

    /**
     * @type {string}
     * @memberof Address
     * @example Palo Alto
     */
    city?: string;

    /**
     * @type {string}
     * @memberof Address
     * @example CA
     */
    state?: string;

    /**
     * @type {string}
     * @memberof Address
     * @example 94301
     */
    zip?: string;
}
