/* tslint:disable */
/* eslint-disable */
/**
 * Swagger Petstore - OpenAPI 3.0
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.11
 * Contact: apiteam@swagger.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface ApiResponse
 */
//APIResponse 인터페이스 정의
export interface ApiResponse {

    /**
     * @type {number}
     * @memberof ApiResponse
     */
    code?: number;

    /**
     * @type {string}
     * @memberof ApiResponse
     */
    type?: string;

    /**
     * @type {string}
     * @memberof ApiResponse
     */
    message?: string;
}
