/* tslint:disable */
/* eslint-disable */
/**
 * Swagger Petstore - OpenAPI 3.0
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.11
 * Contact: apiteam@swagger.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface Category
 */
//카테고리 인터페이스 정의, 아이디는 선택사항, 이름도 선택사항
export interface Category {

    /**
     * @type {number}
     * @memberof Category
     * @example 1
     */
    id?: number;

    /**
     * @type {string}
     * @memberof Category
     * @example Dogs
     */
    name?: string;
}
