/* tslint:disable */
/* eslint-disable */
/**
 * Swagger Petstore - OpenAPI 3.0
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.11
 * Contact: apiteam@swagger.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { Address } from './address';
 /**
 * 
 *
 * @export
 * @interface Customer
 */
export interface Customer {

    /**
     * @type {number}
     * @memberof Customer
     * @example 100000
     */
    id?: number;

    /**
     * @type {string}
     * @memberof Customer
     * @example fehguy
     */
    username?: string;

    /**
     * @type {Array<Address>}
     * @memberof Customer
     */
    address?: Array<Address>;
}
