/* tslint:disable */
/* eslint-disable */
/**
 * Swagger Petstore - OpenAPI 3.0
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.11
 * Contact: apiteam@swagger.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface Order
 */
export interface Order {

    /**
     * @type {number}
     * @memberof Order
     * @example 10
     */
    id?: number;

    /**
     * @type {number}
     * @memberof Order
     * @example 198772
     */
    petId?: number;

    /**
     * @type {number}
     * @memberof Order
     * @example 7
     */
    quantity?: number;

    /**
     * @type {Date}
     * @memberof Order
     */
    shipDate?: Date;

    /**
     * Order Status
     *
     * @type {string}
     * @memberof Order
     * @example approved
     */
    status?: OrderStatusEnum;

    /**
     * @type {boolean}
     * @memberof Order
     */
    complete?: boolean;
}

/**
 * @export
 * @enum {string}
 */
export enum OrderStatusEnum {
    Placed = 'placed',
    Approved = 'approved',
    Delivered = 'delivered'
}

