/* tslint:disable */
/* eslint-disable */
/**
 * Swagger Petstore - OpenAPI 3.0
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.11
 * Contact: apiteam@swagger.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { Category } from './category';
import { Tag } from './tag';
 /**
 * 
 *
 * @export
 * @interface Pet
 */
export interface Pet {

    /**
     * @type {number}
     * @memberof Pet
     * @example 10
     */
    id?: number;

    /**
     * @type {string}
     * @memberof Pet
     * @example doggie
     */
    name: string;

    /**
     * @type {Category}
     * @memberof Pet
     */
    category?: Category;

    /**
     * @type {Array<string>}
     * @memberof Pet
     */
    photoUrls: Array<string>;

    /**
     * @type {Array<Tag>}
     * @memberof Pet
     */
    tags?: Array<Tag>;

    /**
     * pet status in the store
     *
     * @type {string}
     * @memberof Pet
     */
    status?: PetStatusEnum;
}

/**
 * @export
 * @enum {string}
 */
export enum PetStatusEnum {
    Available = 'available',
    Pending = 'pending',
    Sold = 'sold'
}

