/* tslint:disable */
/* eslint-disable */
/**
 * Swagger Petstore - OpenAPI 3.0
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.11
 * Contact: apiteam@swagger.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface User
 */
export interface User {

    /**
     * @type {number}
     * @memberof User
     * @example 10
     */
    id?: number;

    /**
     * @type {string}
     * @memberof User
     * @example theUser
     */
    username?: string;

    /**
     * @type {string}
     * @memberof User
     * @example John
     */
    firstName?: string;

    /**
     * @type {string}
     * @memberof User
     * @example James
     */
    lastName?: string;

    /**
     * @type {string}
     * @memberof User
     * @example john@email.com
     */
    email?: string;

    /**
     * @type {string}
     * @memberof User
     * @example 12345
     */
    password?: string;

    /**
     * @type {string}
     * @memberof User
     * @example 12345
     */
    phone?: string;

    /**
     * User Status
     *
     * @type {number}
     * @memberof User
     * @example 1
     */
    userStatus?: number;
}
